# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-25 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_authenticationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledpost',
            name='attached_media',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
