# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-05 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_scheduledpost_attached_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledpost',
            name='attached_media',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y%m%d'),
        ),
        migrations.AlterField(
            model_name='scheduledpost',
            name='service',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter')], max_length=20),
        ),
    ]
