# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_auto_20170112_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledpost',
            name='extra',
            field=models.TextField(default='{}'),
        ),
    ]
